insert into ai_coding_oss_top5_items (
  brief_date,
  digest_rank,
  repo_owner,
  repo_name,
  project_name,
  repo_url,
  positioning,
  primary_language,
  momentum_text,
  recent_update_text,
  recent_update_date,
  labels,
  brief_summary,
  source_links,
  metadata
)
values
(
  date '2026-06-29',
  1,
  'JCodesMore',
  'ai-website-cloner-template',
  'JCodesMore/ai-website-cloner-template',
  'https://github.com/JCodesMore/ai-website-cloner-template',
  '把网页逆向、组件拆解和前端复刻流程封装成一键可跑的 AI 编码模板，适合 Claude Code 一类代理直接接手。',
  'TypeScript',
  'Trending TypeScript +782 stars today；总 Stars 23,205 / Forks 3,318',
  'GitHub API：repo updated_at 2026-06-29；latest push 2026-06-01',
  date '2026-06-29',
  array['网站克隆', 'Claude Code', 'Agent 模板']::text[],
  '近 24 小时热度继续向“可复用 AI 编码基础设施”集中：网站克隆模板、Agent 技能分发、多模型编码网关、终端代码代理和 Agent 设计原则同步走强；Claude Code、MCP 与上下文治理仍是扩散最快的主题。',
  '["https://github.com/trending/typescript?since=daily","https://github.com/JCodesMore/ai-website-cloner-template"]'::jsonb,
  '{"rank_basis":"stars_today_desc","stars_today":782,"stars_total":23205,"forks_total":3318,"trend_page":"https://github.com/trending/typescript?since=daily"}'::jsonb
),
(
  date '2026-06-29',
  2,
  'vercel-labs',
  'skills',
  'vercel-labs/skills',
  'https://github.com/vercel-labs/skills',
  '把可复用 agent skills 做成统一安装与分发工具，直接服务 Claude Code 和多代理开发工作流复用。',
  'TypeScript',
  'Trending TypeScript +250 stars today；总 Stars 24,190 / Forks 1,981',
  'Latest release v1.5.13，2026-06-23',
  date '2026-06-23',
  array['Agent 技能', 'Claude Code', '开发工作流']::text[],
  '近 24 小时热度继续向“可复用 AI 编码基础设施”集中：网站克隆模板、Agent 技能分发、多模型编码网关、终端代码代理和 Agent 设计原则同步走强；Claude Code、MCP 与上下文治理仍是扩散最快的主题。',
  '["https://github.com/trending/typescript?since=daily","https://github.com/vercel-labs/skills","https://github.com/vercel-labs/skills/releases"]'::jsonb,
  '{"rank_basis":"stars_today_desc","stars_today":250,"stars_total":24190,"forks_total":1981,"latest_release":"v1.5.13","latest_release_date":"2026-06-23"}'::jsonb
),
(
  date '2026-06-29',
  3,
  'diegosouzapw',
  'OmniRoute',
  'diegosouzapw/OmniRoute',
  'https://github.com/diegosouzapw/OmniRoute',
  '给 Claude Code、Codex、Cursor、Cline 等编码客户端提供统一多模型接入、压缩和自动回退网关。',
  'TypeScript',
  'Trending TypeScript +155 stars today；总 Stars 7,639 / Forks 1,295',
  'Latest release v3.8.39，2026-06-28',
  date '2026-06-28',
  array['编码网关', 'MCP', '多模型路由']::text[],
  '近 24 小时热度继续向“可复用 AI 编码基础设施”集中：网站克隆模板、Agent 技能分发、多模型编码网关、终端代码代理和 Agent 设计原则同步走强；Claude Code、MCP 与上下文治理仍是扩散最快的主题。',
  '["https://github.com/trending/typescript?since=daily","https://github.com/diegosouzapw/OmniRoute","https://github.com/diegosouzapw/OmniRoute/releases"]'::jsonb,
  '{"rank_basis":"stars_today_desc","stars_today":155,"stars_total":7639,"forks_total":1295,"latest_release":"v3.8.39","latest_release_date":"2026-06-28"}'::jsonb
),
(
  date '2026-06-29',
  4,
  'CodebuffAI',
  'codebuff',
  'CodebuffAI/codebuff',
  'https://github.com/CodebuffAI/codebuff',
  '面向终端的开源代码生成代理，强调在 CLI 里直接完成生成、修改与执行闭环。',
  'TypeScript',
  'Trending TypeScript +60 stars today；总 Stars 6,856 / Forks 837',
  'GitHub API：updated_at / pushed_at 2026-06-29',
  date '2026-06-29',
  array['编码代理', '终端代理', '代码生成']::text[],
  '近 24 小时热度继续向“可复用 AI 编码基础设施”集中：网站克隆模板、Agent 技能分发、多模型编码网关、终端代码代理和 Agent 设计原则同步走强；Claude Code、MCP 与上下文治理仍是扩散最快的主题。',
  '["https://github.com/trending/typescript?since=daily","https://github.com/CodebuffAI/codebuff"]'::jsonb,
  '{"rank_basis":"stars_today_desc","stars_today":60,"stars_total":6856,"forks_total":837,"repo_updated_at":"2026-06-29"}'::jsonb
),
(
  date '2026-06-29',
  5,
  'humanlayer',
  '12-factor-agents',
  'humanlayer/12-factor-agents',
  'https://github.com/humanlayer/12-factor-agents',
  '把 LLM 软件工程中的上下文、记忆、工具和编排原则沉淀成可复用 Agent 设计规范，适合做团队内编码标准件。',
  'TypeScript',
  'Trending TypeScript +31 stars today；总 Stars 23,647 / Forks 1,816',
  'GitHub API：repo updated_at 2026-06-29',
  date '2026-06-29',
  array['Agent 设计', '长期记忆', '设计规范']::text[],
  '近 24 小时热度继续向“可复用 AI 编码基础设施”集中：网站克隆模板、Agent 技能分发、多模型编码网关、终端代码代理和 Agent 设计原则同步走强；Claude Code、MCP 与上下文治理仍是扩散最快的主题。',
  '["https://github.com/trending/typescript?since=daily","https://github.com/humanlayer/12-factor-agents"]'::jsonb,
  '{"rank_basis":"stars_today_desc","stars_today":31,"stars_total":23647,"forks_total":1816,"repo_updated_at":"2026-06-29"}'::jsonb
)
on conflict (brief_date, repo_url) do update
set
  digest_rank = excluded.digest_rank,
  repo_owner = excluded.repo_owner,
  repo_name = excluded.repo_name,
  project_name = excluded.project_name,
  positioning = excluded.positioning,
  primary_language = excluded.primary_language,
  momentum_text = excluded.momentum_text,
  recent_update_text = excluded.recent_update_text,
  recent_update_date = excluded.recent_update_date,
  labels = excluded.labels,
  brief_summary = excluded.brief_summary,
  source_links = excluded.source_links,
  metadata = excluded.metadata,
  digest_run_at = now(),
  updated_at = now();
