INSERT INTO ai_coding_oss_top5_items (
  brief_date,
  digest_run_at,
  digest_rank,
  repo_owner,
  repo_name,
  project_name,
  repo_url,
  positioning,
  primary_language,
  momentum_text,
  recent_update_text,
  recent_update_date,
  labels,
  brief_summary,
  source_links,
  metadata
)
VALUES
(
  DATE '2026-07-07',
  NOW(),
  1,
  'addyosmani',
  'agent-skills',
  'agent-skills',
  'https://github.com/addyosmani/agent-skills',
  '把资深工程师的规范、测试、评审与交付流程封装成可复用技能，直接喂给 AI 编码代理。',
  'JavaScript',
  'GitHub Trending：1,112 stars today；总星标 71.1k',
  'Latest release 0.6.3 · 2026-07-03',
  DATE '2026-07-03',
  ARRAY['编码代理','工程规范','代码评审']::text[],
  '过去 24 小时榜单继续由“给编码代理加能力”的仓库领跑：技能包、跨代理桥接和终端编排最强势。Top5 全都带有清晰开发工作流属性，热点已从单点写代码转向可组合、可审查、可集成的代理工程化。',
  '[{"label":"GitHub Trending","url":"https://github.com/trending"},{"label":"Repository","url":"https://github.com/addyosmani/agent-skills"},{"label":"Releases","url":"https://github.com/addyosmani/agent-skills/releases"}]'::jsonb,
  '{"rank_basis":"stars_today_then_relevance","stars_today":1112,"total_stars_text":"71.1k","release_version":"0.6.3","release_date":"2026-07-03","source_scope":["github_trending","github_repo","github_releases"]}'::jsonb
),
(
  DATE '2026-07-07',
  NOW(),
  2,
  'openai',
  'codex-plugin-cc',
  'codex-plugin-cc',
  'https://github.com/openai/codex-plugin-cc',
  '把 Codex 接到 Claude Code 工作流里，用于委派任务与代码审查，是典型的跨代理协作桥接层。',
  'JavaScript',
  'GitHub Trending：906 stars today；总星标 26.4k',
  'Latest release v1.0.5 · 2026-06-23',
  DATE '2026-06-23',
  ARRAY['Claude Code','代码评审','代理桥接']::text[],
  '过去 24 小时榜单继续由“给编码代理加能力”的仓库领跑：技能包、跨代理桥接和终端编排最强势。Top5 全都带有清晰开发工作流属性，热点已从单点写代码转向可组合、可审查、可集成的代理工程化。',
  '[{"label":"GitHub Trending","url":"https://github.com/trending"},{"label":"Repository","url":"https://github.com/openai/codex-plugin-cc"},{"label":"Releases","url":"https://github.com/openai/codex-plugin-cc/releases"}]'::jsonb,
  '{"rank_basis":"stars_today_then_relevance","stars_today":906,"total_stars_text":"26.4k","release_version":"v1.0.5","release_date":"2026-06-23","source_scope":["github_trending","github_repo","github_releases"]}'::jsonb
),
(
  DATE '2026-07-07',
  NOW(),
  3,
  'ogulcancelik',
  'herdr',
  'herdr',
  'https://github.com/ogulcancelik/herdr',
  '在终端里统一调度多个 coding agent，会话切换、路由和代理编排都围绕开发者工作台展开。',
  'Rust',
  'GitHub Trending：779 stars today；总星标 13.1k',
  'Latest release v0.7.1 · 2026-06-24',
  DATE '2026-06-24',
  ARRAY['终端代理','多代理编排','工作流路由']::text[],
  '过去 24 小时榜单继续由“给编码代理加能力”的仓库领跑：技能包、跨代理桥接和终端编排最强势。Top5 全都带有清晰开发工作流属性，热点已从单点写代码转向可组合、可审查、可集成的代理工程化。',
  '[{"label":"GitHub Trending","url":"https://github.com/trending"},{"label":"Repository","url":"https://github.com/ogulcancelik/herdr"},{"label":"Releases","url":"https://github.com/ogulcancelik/herdr/releases"}]'::jsonb,
  '{"rank_basis":"stars_today_then_relevance","stars_today":779,"total_stars_text":"13.1k","release_version":"v0.7.1","release_date":"2026-06-24","source_scope":["github_trending","github_repo","github_releases"]}'::jsonb
),
(
  DATE '2026-07-07',
  NOW(),
  4,
  'alirezarezvani',
  'claude-skills',
  'claude-skills',
  'https://github.com/alirezarezvani/claude-skills',
  '超大规模技能与插件仓，覆盖 Claude Code、Codex、Cursor 等多种 coding agent 的能力扩展。',
  'Python',
  'GitHub Trending：610 stars today；总星标 21.3k',
  'Latest release v2.9.0 · 2026-05-28',
  DATE '2026-05-28',
  ARRAY['技能仓','Codex','Agent 模板']::text[],
  '过去 24 小时榜单继续由“给编码代理加能力”的仓库领跑：技能包、跨代理桥接和终端编排最强势。Top5 全都带有清晰开发工作流属性，热点已从单点写代码转向可组合、可审查、可集成的代理工程化。',
  '[{"label":"GitHub Trending","url":"https://github.com/trending"},{"label":"Repository","url":"https://github.com/alirezarezvani/claude-skills"},{"label":"Releases","url":"https://github.com/alirezarezvani/claude-skills/releases"}]'::jsonb,
  '{"rank_basis":"stars_today_then_relevance","stars_today":610,"total_stars_text":"21.3k","release_version":"v2.9.0","release_date":"2026-05-28","source_scope":["github_trending","github_repo","github_releases"]}'::jsonb
),
(
  DATE '2026-07-07',
  NOW(),
  5,
  'CoplayDev',
  'unity-mcp',
  'unity-mcp',
  'https://github.com/CoplayDev/unity-mcp',
  '把 Unity 编辑器包装成 MCP 可调用能力，让 AI 助手直接操作场景、资源与脚本，偏向游戏开发编码链路。',
  'C#',
  'GitHub Trending：311 stars today；总星标 12.2k',
  'Latest release v10.0.0 · 2026-06-30',
  DATE '2026-06-30',
  ARRAY['MCP','游戏开发','编辑器自动化']::text[],
  '过去 24 小时榜单继续由“给编码代理加能力”的仓库领跑：技能包、跨代理桥接和终端编排最强势。Top5 全都带有清晰开发工作流属性，热点已从单点写代码转向可组合、可审查、可集成的代理工程化。',
  '[{"label":"GitHub Trending C#","url":"https://github.com/trending/c%23"},{"label":"Repository","url":"https://github.com/CoplayDev/unity-mcp"},{"label":"Releases","url":"https://github.com/CoplayDev/unity-mcp/releases"}]'::jsonb,
  '{"rank_basis":"stars_today_then_relevance","stars_today":311,"total_stars_text":"12.2k","release_version":"v10.0.0","release_date":"2026-06-30","source_scope":["github_trending_language","github_repo","github_releases"]}'::jsonb
)
ON CONFLICT (brief_date, repo_url) DO UPDATE
SET
  digest_run_at = EXCLUDED.digest_run_at,
  digest_rank = EXCLUDED.digest_rank,
  repo_owner = EXCLUDED.repo_owner,
  repo_name = EXCLUDED.repo_name,
  project_name = EXCLUDED.project_name,
  positioning = EXCLUDED.positioning,
  primary_language = EXCLUDED.primary_language,
  momentum_text = EXCLUDED.momentum_text,
  recent_update_text = EXCLUDED.recent_update_text,
  recent_update_date = EXCLUDED.recent_update_date,
  labels = EXCLUDED.labels,
  brief_summary = EXCLUDED.brief_summary,
  source_links = EXCLUDED.source_links,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
